services:
  - type: web
    name: brightswagshop-frontend
    root: frontend
    buildCommand: npm ci --production --no-optional && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
